# Generated by Django 4.2 on 2023-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0004_alter_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='meme', max_length=50),
        ),
    ]
