# Generated by Django 4.2 on 2023-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0005_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(default='meme', max_length=200),
        ),
    ]
