# Generated by Django 4.2 on 2024-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0011_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank_pic.jpg', upload_to='profile_images/'),
        ),
    ]
