# Generated by Django 4.2 on 2024-05-04 10:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0012_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('caption', models.TextField(default='funny', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
