# Generated by Django 4.2 on 2024-05-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0013_post_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date',
        ),
    ]
