# Generated by Django 4.2 on 2024-05-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0014_rename_created_at_post_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Image',
        ),
    ]
