# Generated by Django 4.2 on 2024-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0016_likeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
