# Generated by Django 4.2 on 2024-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0019_theprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
