# Generated by Django 4.2 on 2024-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0024_remove_image_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='post_images/'),
        ),
    ]
