# Generated by Django 4.2 on 2024-06-07 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0025_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'mp4', 'mkv', 'webm', 'avi', 'mov', 'gif'])]),
        ),
    ]
