# Generated by Django 4.2 on 2024-06-08 19:50

import django.core.validators
from django.db import migrations, models
import memeshub.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0026_alter_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpg', '.jpeg', '.mp4', '.mkv', '.webm', '.avi', '.mov', '.gif']), memeshub.models.validate_file_mimetype]),
        ),
    ]
