# Generated by Django 4.2 on 2024-06-09 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeshub', '0027_rename_image_comment_file_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
