# Generated by Django 4.2 on 2024-06-10 15:51

from django.db import migrations, models
import memeshub.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0030_alter_image_user_alter_theprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.CharField(default=memeshub.models.generate_uuid, max_length=100, primary_key=True, serialize=False),
        ),
    ]
