# Generated by Django 4.2 on 2024-06-10 15:54

from django.db import migrations, models
import memeshub.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0031_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=memeshub.models.generate_uuid, primary_key=True, serialize=False),
        ),
    ]
